esphome:
  name: espvoice
  name_add_mac_suffix: true
  
  includes:
    - uart_read_line_sensor.h

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: none
  
# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESPVoice WIFI AP"
    password: !secret wifi_ap_password

captive_portal:

uart:
  id: uart_bus
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600

text_sensor: 
  - platform: custom
    lambda: |-
      auto my_custom_sensor = new UartReadLineSensor(id(uart_bus));
      App.register_component(my_custom_sensor);
      return {my_custom_sensor};
  
    text_sensors:
      # id: "uart_readline"
      name: "espvoiceuart"

switch:
  - platform: template
    icon: "mdi:account-voice"
    name: "[Scene Control 01]-Welcome Scene"
    id: "switchWelcomeScene"
    turn_on_action:
      - uart.write: [0xAA, 0x55, 0x31, 0x55, 0xAA]
      - delay: 1s
      - switch.turn_off: switchWelcomeScene
  - platform: template
    name: "[Scene Control 02]-Good Night Scene"
    id: "switchByeScene"
    icon: "mdi:account-voice"
    turn_on_action:
      - uart.write: [0xAA, 0x55, 0x32, 0x55, 0xAA]
      - delay: 1s
      - switch.turn_off: switchByeScene
  - platform: template
    name: "[Scene Control 03]-Morning Scene"
    id: "switchMorningScene"
    icon: "mdi:account-voice"
    turn_on_action:
      - uart.write: [0xAA, 0x55, 0x33, 0x55, 0xAA]
      - delay: 1s
      - switch.turn_off: switchMorningScene
  - platform: template
    name: "[Scene Control 04]-Evening Scene"
    id: "switchEveningScene"
    icon: "mdi:account-voice"
    turn_on_action:
      - uart.write: [0xAA, 0x55, 0x34, 0x55, 0xAA]
      - delay: 1s
      - switch.turn_off: switchEveningScene
  - platform: template
    name: "[Setting 06]-Mute"
    id: "settingMute"
    icon: "mdi:volume-mute"
    optimistic: True
    turn_on_action:
      - uart.write: [0xAA, 0x55, 0x21, 0x55, 0xAA]
    turn_off_action:
      - uart.write: [0xAA, 0x55, 0x22, 0x55, 0xAA]

button:
  - platform: template
    name: "[Setting 01]-Activate Command Recognition"
    id: "settingRecognition"
    icon: "mdi:ear-hearing"
    on_press:
      - uart.write: [0xAA, 0x55, 0x23, 0x55, 0xAA]
  
  - platform: template
    name: "[Setting 02]-Switch on ESP Voice"
    id: "settingDeviceOn"
    icon: "mdi:power"
    on_press:
      - uart.write: [0xAA, 0x55, 0x24, 0x55, 0xAA]
    
  - platform: template
    name: "[Setting 03]-Switch off ESP Voice"
    id: "settingDeviceOff"
    icon: "mdi:power"
    on_press:
      - uart.write: [0xAA, 0x55, 0x25, 0x55, 0xAA]
  
  - platform: template
    name: "[Setting 04]-Auto Reply On"
    id: "settingReplyOn"
    icon: "mdi:reply"
    on_press:
      - uart.write: [0xAA, 0x55, 0x29, 0x55, 0xAA]
  
  - platform: template
    name: "[Setting 05]-Auto Reply Off"
    id: "settingReplyOff"
    icon: "mdi:reply"
    on_press:
      - uart.write: [0xAA, 0x55, 0x28, 0x55, 0xAA]
  
  - platform: template
    name: "[Setting 07]-Low Volume"
    id: "settingVolLow"
    icon: "mdi:volume-low"
    on_press:
      - uart.write: [0xAA, 0x55, 0x2A, 0x55, 0xAA]
  
  - platform: template
    name: "[Setting 08]-Mid Volume"
    id: "settingVolMid"
    icon: "mdi:volume-medium"
    on_press:
      - uart.write: [0xAA, 0x55, 0x2B, 0x55, 0xAA]
  
  - platform: template
    name: "[Setting 09]-High Volume"
    id: "settingVolHigh"
    icon: "mdi:volume-high"
    on_press:
      - uart.write: [0xAA, 0x55, 0x2C, 0x55, 0xAA]
  
  - platform: template
    name: "[Setting 12]-Reset"
    id: "settingRestart"
    icon: "mdi:restart"
    on_press:
      - uart.write: [0xAA, 0x55, 0x2D, 0x55, 0xAA]
  
  - platform: template
    name: "[Setting 13]-Firmware Version"
    id: "settingVersion"
    icon: "mdi:alpha-v-circle-outline"
    on_press:
      - uart.write: [0xAA, 0x55, 0x2E, 0x55, 0xAA]

  - platform: template
    name: "[Learn 00]-Wake Word"
    icon: "mdi:microphone-settings"
    on_press:
      - uart.write: [0xAA, 0x55, 0x0F, 0x55, 0xAA]
  - platform: template
    name: "[Learn 14]-Confirm Phrase"
    icon: "mdi:microphone-settings"
    on_press:
      - uart.write: [0xAA, 0x55, 0x00, 0x55, 0xAA]                 
  - platform: template
    name: "[Learn 01]-Control 01"
    icon: "mdi:microphone-settings"
    on_press:
      - uart.write: [0xAA, 0x55, 0x01, 0x55, 0xAA]
  - platform: template
    name: "[Learn 02]-Control 02"
    icon: "mdi:microphone-settings"
    on_press:
      - uart.write: [0xAA, 0x55, 0x02, 0x55, 0xAA]
  - platform: template
    name: "[Learn 03]-Control 03"
    icon: "mdi:microphone-settings"
    on_press:
      - uart.write: [0xAA, 0x55, 0x03, 0x55, 0xAA]
  - platform: template
    name: "[Learn 04]-Control 04"
    icon: "mdi:microphone-settings"
    on_press:
      - uart.write: [0xAA, 0x55, 0x04, 0x55, 0xAA]
  - platform: template
    name: "[Learn 05]-Control 05"
    icon: "mdi:microphone-settings"
    on_press:
      - uart.write: [0xAA, 0x55, 0x05, 0x55, 0xAA]
  - platform: template
    name: "[Learn 06]-Control 06"
    icon: "mdi:microphone-settings"
    on_press:
      - uart.write: [0xAA, 0x55, 0x06, 0x55, 0xAA]
  - platform: template
    name: "[Learn 07]-Control 07"
    icon: "mdi:microphone-settings"
    on_press:
      - uart.write: [0xAA, 0x55, 0x07, 0x55, 0xAA]
  - platform: template
    name: "[Learn 08]-Control 08"
    icon: "mdi:microphone-settings"
    on_press:
      - uart.write: [0xAA, 0x55, 0x08, 0x55, 0xAA]
  
  - platform: template
    name: "[Learn 09]-Control 09"
    icon: "mdi:microphone-settings"
    on_press:
      - uart.write: [0xAA, 0x55, 0x09, 0x55, 0xAA]
  
  - platform: template
    name: "[Learn 10]-Control 10"
    icon: "mdi:microphone-settings"
    on_press:
      - uart.write: [0xAA, 0x55, 0x0A, 0x55, 0xAA]
  
  - platform: template
    name: "[Learn 11]-Control 11"
    icon: "mdi:microphone-settings"
    on_press:
      - uart.write: [0xAA, 0x55, 0x0B, 0x55, 0xAA]
  
  - platform: template
    name: "[Learn 12]-Control 12"
    icon: "mdi:microphone-settings"
    on_press:
      - uart.write: [0xAA, 0x55, 0x0C, 0x55, 0xAA]
  - platform: template
    name: "[Learn 13]-SOS"
    icon: "mdi:ambulance"
    on_press:
      - uart.write: [0xAA, 0x55, 0x0D, 0x55, 0xAA]
  - platform: template
    name: "[Setting 10]-Volume Up"
    icon: "mdi:volume-plus"
    on_press:
      - uart.write: [0xAA, 0x55, 0x27, 0x55, 0xAA]
  - platform: template
    name: "[Setting 11]-Volume Down"
    icon: "mdi:volume-minus"
    on_press:
      - uart.write: [0xAA, 0x55, 0x26, 0x55, 0xAA]

# PA system
  - platform: template
    name: "[PA 01]-Alarm Beep"
    icon: "mdi:alarm"
    on_press:
      - uart.write: [0xAA, 0x55, 0x40, 0x55, 0xAA]

  - platform: template
    name: "[PA 02]-Siren"
    icon: "mdi:alarm-light"
    on_press:
      - uart.write: [0xAA, 0x55, 0x41, 0x55, 0xAA]

  - platform: template
    name: "[PA 03]-Person at Main Door"
    icon: "mdi:motion-sensor"
    on_press:
      - uart.write: [0xAA, 0x55, 0x42, 0x55, 0xAA]

  - platform: template
    name: "[PA 04]-Person at Back Door"
    icon: "mdi:motion-sensor"
    on_press:
      - uart.write: [0xAA, 0x55, 0x43, 0x55, 0xAA]

  - platform: template
    name: "[PA 05]-Main Door-Opened"
    icon: "mdi:door-open"
    on_press:
      - uart.write: [0xAA, 0x55, 0x44, 0x55, 0xAA]

  - platform: template
    name: "[PA 06]-Main Door-Closed"
    icon: "mdi:door-closed"
    on_press:
      - uart.write: [0xAA, 0x55, 0x45, 0x55, 0xAA]

  - platform: template
    name: "[PA 07]-Garage Door-Opened"
    icon: "mdi:garage-open"
    on_press:
      - uart.write: [0xAA, 0x55, 0x46, 0x55, 0xAA]

  - platform: template
    name: "[PA 08]-Garage Door-Closed"
    icon: "mdi:garage"
    on_press:
      - uart.write: [0xAA, 0x55, 0x47, 0x55, 0xAA]

  - platform: template
    name: "[PA 09]-Window-Opened"
    icon: "mdi:window-open-variant"
    on_press:
      - uart.write: [0xAA, 0x55, 0x48, 0x55, 0xAA]

  - platform: template
    name: "[PA 10]-Window-Closed"
    icon: "mdi:window-closed-variant"
    on_press:
      - uart.write: [0xAA, 0x55, 0x49, 0x55, 0xAA]

  - platform: template
    name: "[PA 11]-Alarm-Armed Away"
    icon: "mdi:shield-lock-outline"
    on_press:
      - uart.write: [0xAA, 0x55, 0x4A, 0x55, 0xAA]

  - platform: template
    name: "[PA 12]-Alarm-Armed Home"
    icon: "mdi:shield-home"
    on_press:
      - uart.write: [0xAA, 0x55, 0x4B, 0x55, 0xAA]

  - platform: template
    name: "[PA 13]-Alarm-Disarmed"
    icon: "mdi:shield-lock-open"
    on_press:
      - uart.write: [0xAA, 0x55, 0x4C, 0x55, 0xAA]

  - platform: template
    name: "[PA 14]-Door Bell"
    icon: "mdi:bell-ring"
    on_press:
      - uart.write: [0xAA, 0x55, 0x4D, 0x55, 0xAA]

